version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
      semver-minor-days: 7
      semver-patch-days: 7
    open-pull-requests-limit: 10
    groups:
      aksel:
        applies-to: version-updates
        patterns:
          - "@navikt/aksel*"
          - "@navikt/ds*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      react-router:
        applies-to: version-updates
        patterns:
          - "@react-router*"
          - "react-router"
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
      testcontainers:
        patterns:
          - "@testcontainers/postgresql"
          - 'testcontainers'
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps):"
