engineStrict: true
autoInstallPeers: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@navikt/*'
  - '@nais/*'
allowBuilds:
  cpu-features: true
  esbuild: true
  lefthook: true
  protobufjs: true
  ssh2: true
