apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kiss
  namespace: team-sdlc
  labels:
    team: team-sdlc
spec:
  image: "{{image}}"
  port: 3000
  replicas:
    min: 1
    max: 1
  liveness:
    path: /api/isalive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /api/isready
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  ingresses:
    - https://kiss.intern.dev.nav.no
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        pointInTimeRecovery: true
        databases:
          - name: kiss
    buckets:
      - name: kiss-data-dev
        retentionPeriodDays: 365
        cascadingDelete: false
  accessPolicy:
    outbound:
      external:
        - host: graph.microsoft.com
