apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kiss
  namespace: pensjon-revisjon
  labels:
    team: pensjon-revisjon
spec:
  image: "{{image}}"
  port: 3000
  replicas:
    min: 2
    max: 2
  liveness:
    path: /api/isalive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /api/isready
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  ingresses:
    - https://kiss.intern.nav.no
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 1e97cbc6-0687-4d23-aebd-c611035279c1  # pensjon-revisjon (admin)
          - id: 415d3817-c83d-44c9-a52b-5116757f8fa8  # teampensjon (user)
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-f1-micro
        pointInTimeRecovery: true
        flags:
          - name: cloudsql.enable_pgaudit
            value: "on"
          - name: pgaudit.log
            value: "all"
        databases:
          - name: kiss
    buckets:
      - name: kiss-data
        retentionPeriodDays: 4015
        cascadingDelete: false
        lifecycleCondition:
          withState: ANY
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    outbound:
      external:
        - host: graph.microsoft.com
        - host: console.nav.cloud.nais.io
  env:
    - name: NODE_ENV
      value: production
    - name: TZ
      value: Europe/Oslo
    - name: NAIS_API_URL
      value: https://console.nav.cloud.nais.io/graphql
    - name: ENABLE_NAIS_SYNC
      value: "true"
  envFrom:
    - secret: kiss
