import { index, type RouteConfig, route } from "@react-router/dev/routes"

export default [
	index("routes/_index/index.tsx"),
	route("kontrollrammeverk", "routes/kontrollrammeverk/index.tsx"),
	route("kontrollrammeverk/risiko/:risikoId", "routes/kontrollrammeverk.risiko.$risikoId/index.tsx"),
	route("kontrollrammeverk/:domene", "routes/kontrollrammeverk.$domene/index.tsx"),
	route("kontrollrammeverk/:domene/:kontrollId", "routes/kontrollrammeverk.$domene.$kontrollId/index.tsx"),
	route(
		"kontrollrammeverk/:domene/:kontrollId/rediger",
		"routes/kontrollrammeverk.$domene.$kontrollId.rediger/index.tsx",
	),
	route("admin/import", "routes/admin.import/index.tsx"),
	route("seksjoner", "routes/seksjoner/index.tsx"),
	route("seksjoner/:seksjon", "routes/seksjoner.$seksjon/index.tsx"),
	route("seksjoner/:seksjon/rediger", "routes/seksjoner.$seksjon.rediger/index.tsx"),
	route("seksjoner/:seksjon/nais-team", "routes/seksjoner.$seksjon.nais-team/index.tsx"),
	route("seksjoner/:seksjon/team/:team", "routes/seksjoner.$seksjon.team.$team/index.tsx"),
	route("seksjoner/:seksjon/team/:team/rediger", "routes/seksjoner.$seksjon.team.$team.rediger/index.tsx"),
	route("seksjoner/:seksjon/rutiner", "routes/seksjoner.$seksjon.rutiner/index.tsx"),
	route("seksjoner/:seksjon/rutiner/ny", "routes/seksjoner.$seksjon.rutiner.ny/index.tsx"),
	route("seksjoner/:seksjon/rutiner/mangler", "routes/seksjoner.$seksjon.rutiner.mangler/index.tsx"),
	route("seksjoner/:seksjon/rutiner/gjennomfort", "routes/seksjoner.$seksjon.rutiner.gjennomfort/index.tsx"),
	route("seksjoner/:seksjon/rutiner/:rutineId", "routes/seksjoner.$seksjon.rutiner.$rutineId/index.tsx"),
	route(
		"seksjoner/:seksjon/rutiner/:rutineId/rediger",
		"routes/seksjoner.$seksjon.rutiner.$rutineId.rediger/index.tsx",
	),
	route(
		"seksjoner/:seksjon/rutiner/:rutineId/gjennomgang/ny",
		"routes/seksjoner.$seksjon.rutiner.$rutineId.gjennomgang.ny/index.tsx",
	),
	route(
		"seksjoner/:seksjon/rutiner/:rutineId/gjennomgang/:gjennomgangId",
		"routes/seksjoner.$seksjon.rutiner.$rutineId.gjennomgang.$gjennomgangId/index.tsx",
	),
	route("api/rutine-vedlegg/:vedleggId", "routes/api.rutine-vedlegg.$vedleggId/index.tsx"),
	route("applikasjoner", "routes/applikasjoner/index.tsx"),
	route("applikasjoner/:appId/detaljer", "routes/applikasjoner.$appId.detaljer/index.tsx"),
	route("applikasjoner/:appId/rediger", "routes/applikasjoner.$appId.rediger/index.tsx"),
	route("applikasjoner/:appId/compliance", "routes/applikasjoner.$appId.compliance/index.tsx"),
	route("rapporter", "routes/rapporter/index.tsx"),
	route("rapporter/generer", "routes/rapporter.generer/index.tsx"),
	route("rapporter/:rapportId", "routes/rapporter.$rapportId/index.tsx"),
	route("api/rapporter/:rapportId/pdf", "routes/api.rapporter.$rapportId.pdf/index.tsx"),
	route("api/rapporter/:rapportId/xlsx", "routes/api.rapporter.$rapportId.xlsx/index.tsx"),
	route("nais-overvaking", "routes/nais-overvaking/index.tsx"),
	route("nais-overvaking/endringslogg", "routes/nais-overvaking.endringslogg/index.tsx"),
	route("nais-overvaking/:team", "routes/nais-overvaking.$team/index.tsx"),
	route("admin", "routes/admin/index.tsx"),
	route("admin/seksjoner", "routes/admin.seksjoner/index.tsx"),
	route("admin/screening", "routes/admin.screening/index.tsx"),
	route("admin/screening/:questionId/rediger", "routes/admin.screening.$questionId.rediger/index.tsx"),
	route("admin/link-suggestions", "routes/admin.link-suggestions/index.tsx"),
	route("admin/domener", "routes/admin.domener/index.tsx"),
	route("admin/teknologielementer", "routes/admin.teknologielementer/index.tsx"),
	route("api/isalive", "routes/api.isalive/index.tsx"),
	route("api/isready", "routes/api.isready/index.tsx"),
	route("api/nais-sync", "routes/api.nais-sync/index.tsx"),
	route("api/theme", "routes/api.theme/index.tsx"),
	route("api/search", "routes/api.search/index.tsx"),
	route("api/applikasjoner/:appId/export-xlsx", "routes/api.applikasjoner.$appId.export-xlsx/index.tsx"),
	route("dokumenter", "routes/dokumenter/index.tsx"),
	route("hjelp/markdown", "routes/hjelp.markdown/index.tsx"),
	route("api/dokumenter/:dokumentId", "routes/api.dokumenter.$dokumentId/index.tsx"),
] satisfies RouteConfig
