import { index, type RouteConfig, route } from "@react-router/dev/routes"

export default [
	index("routes/_index/index.tsx"),
	route("kontrollrammeverk", "routes/kontrollrammeverk/index.tsx"),
	route("kontrollrammeverk/risiko/:risikoId", "routes/kontrollrammeverk.risiko.$risikoId/index.tsx"),
	route("kontrollrammeverk/:domene", "routes/kontrollrammeverk.$domene/index.tsx"),
	route("kontrollrammeverk/:domene/:kontrollId", "routes/kontrollrammeverk.$domene.$kontrollId/index.tsx"),
	route("admin/import", "routes/admin.import/index.tsx"),
	route("seksjoner", "routes/seksjoner/index.tsx"),
	route("seksjoner/:seksjon", "routes/seksjoner.$seksjon/index.tsx"),
	route("seksjoner/:seksjon/nais-team", "routes/seksjoner.$seksjon.nais-team/index.tsx"),
	route("seksjoner/:seksjon/team/:team", "routes/seksjoner.$seksjon.team.$team/index.tsx"),
	route("applikasjoner", "routes/applikasjoner/index.tsx"),
	route("applikasjoner/:appId/detaljer", "routes/applikasjoner.$appId.detaljer/index.tsx"),
	route("applikasjoner/:appId/compliance", "routes/applikasjoner.$appId.compliance/index.tsx"),
	route("rapporter", "routes/rapporter/index.tsx"),
	route("rapporter/generer", "routes/rapporter.generer/index.tsx"),
	route("rapporter/:rapportId", "routes/rapporter.$rapportId/index.tsx"),
	route("nais-overvaking", "routes/nais-overvaking/index.tsx"),
	route("nais-overvaking/:team", "routes/nais-overvaking.$team/index.tsx"),
	route("admin", "routes/admin/index.tsx"),
	route("admin/seksjoner", "routes/admin.seksjoner/index.tsx"),
	route("api/isalive", "routes/api.isalive/index.tsx"),
	route("api/isready", "routes/api.isready/index.tsx"),
	route("api/nais-sync", "routes/api.nais-sync/index.tsx"),
	route("api/theme", "routes/api.theme/index.tsx"),
	route("api/search", "routes/api.search/index.tsx"),
	route("api/applikasjoner/:appId/export-xlsx", "routes/api.applikasjoner.$appId.export-xlsx/index.tsx"),
] satisfies RouteConfig
