import { index, type RouteConfig, route } from "@react-router/dev/routes"

export default [
	index("routes/_index/index.tsx"),
	route("dashboard", "routes/dashboard/index.tsx"),
	route("profil", "routes/profil/index.tsx"),
	route("mine-team", "routes/mine-team/index.tsx"),
	// Mine-team-context app routes (breadcrumbs reflect mine-team origin)
	route("mine-team/applikasjoner/:appId/detaljer", "routes/ctx-mine-team.applikasjoner.$appId.detaljer/index.tsx"),
	route("mine-team/applikasjoner/:appId/rediger", "routes/ctx-mine-team.applikasjoner.$appId.rediger/index.tsx"),
	route("mine-team/applikasjoner/:appId/compliance", "routes/ctx-mine-team.applikasjoner.$appId.compliance/index.tsx"),
	route(
		"mine-team/applikasjoner/:appId/compliance-krav",
		"routes/ctx-mine-team.applikasjoner.$appId.compliance-krav/index.tsx",
	),
	route("kontrollrammeverk", "routes/kontrollrammeverk/index.tsx"),
	route("kontrollrammeverk/risiko/:risikoId", "routes/kontrollrammeverk.risiko.$risikoId/index.tsx"),
	route("kontrollrammeverk/:domene", "routes/kontrollrammeverk.$domene/index.tsx"),
	route("kontrollrammeverk/:domene/:kontrollId", "routes/kontrollrammeverk.$domene.$kontrollId/index.tsx"),
	route(
		"kontrollrammeverk/:domene/:kontrollId/rediger",
		"routes/kontrollrammeverk.$domene.$kontrollId.rediger/index.tsx",
	),
	route("admin/import", "routes/admin.import/index.tsx"),
	route("seksjoner", "routes/seksjoner/index.tsx"),
	route("seksjoner/:seksjon", "routes/seksjoner.$seksjon/index.tsx"),
	route("seksjoner/:seksjon/applikasjoner", "routes/seksjoner.$seksjon.applikasjoner/index.tsx"),
	route("seksjoner/:seksjon/rediger", "routes/seksjoner.$seksjon.rediger/index.tsx"),
	route("seksjoner/:seksjon/nais-team", "routes/seksjoner.$seksjon.nais-team/index.tsx"),
	route("seksjoner/:seksjon/team/:team", "routes/seksjoner.$seksjon.team.$team/index.tsx"),
	route("seksjoner/:seksjon/team/:team/rediger", "routes/seksjoner.$seksjon.team.$team.rediger/index.tsx"),
	// Team-context app routes (breadcrumbs reflect team origin)
	route(
		"seksjoner/:seksjon/team/:team/applikasjoner/:appId/detaljer",
		"routes/ctx-team.applikasjoner.$appId.detaljer/index.tsx",
	),
	route(
		"seksjoner/:seksjon/team/:team/applikasjoner/:appId/rediger",
		"routes/ctx-team.applikasjoner.$appId.rediger/index.tsx",
	),
	route(
		"seksjoner/:seksjon/team/:team/applikasjoner/:appId/compliance",
		"routes/ctx-team.applikasjoner.$appId.compliance/index.tsx",
	),
	route(
		"seksjoner/:seksjon/team/:team/applikasjoner/:appId/compliance-krav",
		"routes/ctx-team.applikasjoner.$appId.compliance-krav/index.tsx",
	),
	route("seksjoner/:seksjon/rutiner", "routes/seksjoner.$seksjon.rutiner/index.tsx"),
	route("seksjoner/:seksjon/rutiner/ny", "routes/seksjoner.$seksjon.rutiner.ny/index.tsx"),
	route("seksjoner/:seksjon/rutiner/mangler", "routes/seksjoner.$seksjon.rutiner.mangler/index.tsx"),
	route("seksjoner/:seksjon/rutiner/gjennomfort", "routes/seksjoner.$seksjon.rutiner.gjennomfort/index.tsx"),
	route("seksjoner/:seksjon/rutiner/:rutineId", "routes/seksjoner.$seksjon.rutiner.$rutineId/index.tsx"),
	route(
		"seksjoner/:seksjon/rutiner/:rutineId/rediger",
		"routes/seksjoner.$seksjon.rutiner.$rutineId.rediger/index.tsx",
	),
	route(
		"seksjoner/:seksjon/rutiner/:rutineId/gjennomgang/ny",
		"routes/seksjoner.$seksjon.rutiner.$rutineId.gjennomgang.ny/index.tsx",
	),
	route(
		"seksjoner/:seksjon/rutiner/:rutineId/gjennomgang/:gjennomgangId",
		"routes/seksjoner.$seksjon.rutiner.$rutineId.gjennomgang.$gjennomgangId/index.tsx",
	),
	route("seksjoner/:seksjon/audit-logging", "routes/seksjoner.$seksjon.audit-logging/index.tsx"),
	route("seksjoner/:seksjon/koblingsforslag", "routes/seksjoner.$seksjon.koblingsforslag/index.tsx"),
	route("seksjoner/:seksjon/screening", "routes/seksjoner.$seksjon.screening/index.tsx"),
	route(
		"seksjoner/:seksjon/screening/:questionId/rediger",
		"routes/seksjoner.$seksjon.screening.$questionId.rediger/index.tsx",
	),
	route("seksjoner/:seksjon/regelsett", "routes/seksjoner.$seksjon.regelsett/index.tsx"),
	route("seksjoner/:seksjon/regelsett/ny", "routes/seksjoner.$seksjon.regelsett.ny/index.tsx"),
	route("seksjoner/:seksjon/regelsett/:regelSettId", "routes/seksjoner.$seksjon.regelsett.$regelSettId/index.tsx"),
	route(
		"seksjoner/:seksjon/regelsett/:regelSettId/rediger",
		"routes/seksjoner.$seksjon.regelsett.$regelSettId.rediger/index.tsx",
	),
	route("api/rutine-vedlegg/:vedleggId", "routes/api.rutine-vedlegg.$vedleggId/index.tsx"),
	route("api/gjennomgang/:gjennomgangId/vedlegg", "routes/api.gjennomgang.$gjennomgangId.vedlegg/index.tsx"),
	route("applikasjoner/:appId/detaljer", "routes/applikasjoner.$appId.detaljer/index.tsx"),
	route("applikasjoner/:appId/rediger", "routes/applikasjoner.$appId.rediger/index.tsx"),
	route("applikasjoner/:appId/compliance", "routes/applikasjoner.$appId.compliance/index.tsx"),
	route("applikasjoner/:appId/compliance-krav", "routes/applikasjoner.$appId.compliance-krav/index.tsx"),
	route("api/rapporter/:rapportId/pdf", "routes/api.rapporter.$rapportId.pdf/index.tsx"),
	route("api/rapporter/:rapportId/xlsx", "routes/api.rapporter.$rapportId.xlsx/index.tsx"),
	route("admin/nais-overvaking", "routes/nais-overvaking/index.tsx"),
	route("admin/nais-overvaking/endringslogg", "routes/nais-overvaking.endringslogg/index.tsx"),
	route("admin/nais-overvaking/:team", "routes/nais-overvaking.$team/index.tsx"),
	route("admin", "routes/admin/index.tsx"),
	route("admin/seksjoner", "routes/admin.seksjoner/index.tsx"),
	route("admin/brukere", "routes/admin.brukere/index.tsx"),
	route("admin/screening", "routes/admin.screening/index.tsx"),
	route("admin/screening/:questionId/rediger", "routes/admin.screening.$questionId.rediger/index.tsx"),
	route("admin/domener", "routes/admin.domener/index.tsx"),
	route("admin/teknologielementer", "routes/admin.teknologielementer/index.tsx"),
	route("api/isalive", "routes/api.isalive/index.tsx"),
	route("api/isready", "routes/api.isready/index.tsx"),
	route("api/nais-sync", "routes/api.nais-sync/index.tsx"),
	route("api/search", "routes/api.search/index.tsx"),
	route("api/applikasjoner/:appId/export-xlsx", "routes/api.applikasjoner.$appId.export-xlsx/index.tsx"),
	route("api/applikasjoner/:appId/rapport-pdf", "routes/api.applikasjoner.$appId.rapport-pdf/index.tsx"),
	route(
		"api/applikasjoner/:appId/revisjonsbevis/:instanceId/excel",
		"routes/api.applikasjoner.$appId.revisjonsbevis.$instanceId.excel/index.tsx",
	),
	route("api/revisjonsbevis/:snapshotId/excel", "routes/api.revisjonsbevis.$snapshotId.excel/index.tsx"),
	route("admin/dokumenter", "routes/dokumenter/index.tsx"),
	route("hjelp/markdown", "routes/hjelp.markdown/index.tsx"),
	route("api/dokumenter/:dokumentId", "routes/api.dokumenter.$dokumentId/index.tsx"),
	route("api/seksjoner/:seksjon/eksport", "routes/api.seksjoner.$seksjon.eksport/index.tsx"),
	route("api/eksport/screening", "routes/api.eksport.screening/index.tsx"),
	route("api/graph/groups", "routes/api.graph.groups/index.tsx"),
] satisfies RouteConfig
