import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core"

export const auditLogActionEnum = [
	"framework_imported",
	"framework_activated",
	"framework_archived",
	"risk_short_title_updated",
	"control_short_title_updated",
	"section_created",
	"section_updated",
	"section_deleted",
	"team_created",
	"team_updated",
	"team_deleted",
	"nais_team_status_updated",
	"nais_team_section_linked",
	"nais_team_section_unlinked",
	"nais_sync_completed",
	"app_team_linked",
	"app_team_unlinked",
	"control_field_updated",
	"report_generated",
	"section_app_ignored",
	"section_app_unignored",
	"nais_persistence_synced",
	"application_linked",
	"application_unlinked",
	"predefined_answer_created",
	"predefined_answer_updated",
	"predefined_answer_deleted",
	"screening_question_created",
	"screening_question_updated",
	"screening_question_deleted",
	"screening_answer_saved",
	"domain_created",
	"domain_updated",
	"domain_deleted",
	"risk_domain_changed",
	"technology_element_created",
	"technology_element_updated",
	"technology_element_deleted",
	"control_element_added",
	"control_element_removed",
	"document_uploaded",
	"document_deleted",
	"control_dependency_added",
	"control_dependency_removed",
	"technology_element_confirmed",
	"technology_element_rejected",
	"dev_team_nais_team_linked",
	"dev_team_nais_team_unlinked",
	"routine_created",
	"routine_updated",
	"routine_deleted",
	"routine_review_created",
	"routine_review_updated",
	"routine_review_completed",
	"routine_review_discarded",
	"routine_review_confirmed",
	"routine_attachment_uploaded",
	"review_link_added",
	"review_link_deleted",
	"audit_confirmation_created",
	"audit_confirmation_updated",
	"audit_confirmation_revoked",
	"audit_summary_synced",
	"deployment_verification_synced",
	"application_renamed",
	"application_primary_changed",
	"application_deleted",
	"persistence_added",
	"persistence_updated",
	"persistence_deleted",
	"screening_routine_selected",
	"manual_group_added",
	"manual_group_removed",
	"group_criticality_updated",
	"section_environment_excluded",
	"section_environment_included",
	"review_activity_created",
	"review_activity_completed",
	"review_activity_entra_change",
	"routine_approved",
	"routine_copied",
	"routine_replaced",
	"group_classification_updated",
	"nais_persistence_added",
	"nais_persistence_updated",
	"nais_auth_integration_added",
	"nais_auth_integration_updated",
] as const

export type AuditLogAction = (typeof auditLogActionEnum)[number]

export const auditLog = pgTable("audit_log", {
	id: uuid("id").primaryKey().defaultRandom(),
	action: text("action", { enum: auditLogActionEnum }).notNull(),
	entityType: text("entity_type").notNull(),
	entityId: text("entity_id").notNull(),
	previousValue: text("previous_value"),
	newValue: text("new_value"),
	metadata: text("metadata"),
	performedBy: text("performed_by").notNull(),
	performedAt: timestamp("performed_at", { withTimezone: true }).notNull().defaultNow(),
})
